[versions]
fastutil = "8.5.15"

kotlin = "2.0.0"
dokka = "2.1.0"

[libraries]
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
